In [3]:
import pandas as pd
import numpy as np
data = pd.read_csv("C:\\Users\\Rabat\\Downloads\\General\\General\\02 Набор данных\\with_closed_ations_as________select_app_2020_X5_STORES.CSV")
data


D:\anaconda\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (6,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


id_applicant  id_partner  id_log  department_id  \
0            4797513     3847682      -1           7335   
1            4545953     3714199      -1          24522   
2            4600098     3714199      -1          24522   
3            4788965     3843286      -1          10613   
4            4777310     2372866      -1          45445   
...              ...         ...     ...            ...   
739676       4736341      936507      -1          32061   
739677       4734680     2232021      -1          32061   
739678       4782853     2753502      -1          32110   
739679       4769924     3823657      -1          32110   
739680       4683816      862865      -1          32093   

                          action_date          stage_name  \
0       2020-03-23 19:57:25.316022+00  Создание кандидата   
1       2020-01-24 16:57:59.521103+00  Создание кандидата   
2       2020-02-05 17:57:55.727051+00  Создание кандидата   
3       2020-03-20 16:09:34.454329+00  Создание кандидата   
4       2020-03-18 13:53:36.124784+00  Создание кандидата   
...                               ...                 ...   
739676   2020-04-23 16:26:11.80918+00        Не прошел СБ   
739677   2020-04-23 16:26:11.80918+00       Гайд-интервью   
739678   2020-04-23 16:26:11.80918+00        Не прошел СБ   
739679   2020-04-23 16:26:11.80918+00        Не прошел СБ   
739680   2020-04-23 16:26:11.80918+00        Не прошел СБ   

                            activity_name result_name      position_name  \
0                                     NaN         NaN    Продавец-кассир   
1                                     NaN         NaN  Директор магазина   
2                                     NaN         NaN  Директор магазина   
3                                     NaN         NaN    Продавец-кассир   
4                                     NaN         NaN    Продавец-кассир   
...                                   ...         ...                ...   
739676          Вывести из черного списка         NaN    Продавец-кассир   
739677  Назначить время для гайд-интервью         NaN      Администратор   
739678          Вывести из черного списка         NaN    Продавец-кассир   
739679          Вывести из черного списка         NaN    Продавец-кассир   
739680          Вывести из черного списка         NaN    Продавец-кассир   

        is_active_action  is_open_action  
0                   True           False  
1                   True           False  
2                   True           False  
3                   True           False  
4                   True           False  
...                  ...             ...  
739676              True            True  
739677              True            True  
739678              True            True  
739679              True            True  
739680              True            True  

[739681 rows x 11 columns]

In [56]:
le_masque = data['position_name'] == 'Продавец-кассир'
le_masque &= data['is_active_action'] == True
df = data[le_masque]
df

id_applicant  id_partner  id_log  department_id  \
0            4797513     3847682      -1           7335   
3            4788965     3843286      -1          10613   
4            4777310     2372866      -1          45445   
11           4798971     1253935      -1           9851   
13           4637426     3352131      -1           7640   
...              ...         ...     ...            ...   
739675       4825142     2952699      -1          32061   
739676       4736341      936507      -1          32061   
739678       4782853     2753502      -1          32110   
739679       4769924     3823657      -1          32110   
739680       4683816      862865      -1          32093   

                          action_date          stage_name  \
0       2020-03-23 19:57:25.316022+00  Создание кандидата   
3       2020-03-20 16:09:34.454329+00  Создание кандидата   
4       2020-03-18 13:53:36.124784+00  Создание кандидата   
11      2020-03-24 10:39:28.667648+00  Создание кандидата   
13      2020-02-13 12:44:35.802112+00  Создание кандидата   
...                               ...                 ...   
739675   2020-04-23 16:26:11.80918+00        Не прошел СБ   
739676   2020-04-23 16:26:11.80918+00        Не прошел СБ   
739678   2020-04-23 16:26:11.80918+00        Не прошел СБ   
739679   2020-04-23 16:26:11.80918+00        Не прошел СБ   
739680   2020-04-23 16:26:11.80918+00        Не прошел СБ   

                    activity_name result_name    position_name  \
0                             NaN         NaN  Продавец-кассир   
3                             NaN         NaN  Продавец-кассир   
4                             NaN         NaN  Продавец-кассир   
11                            NaN         NaN  Продавец-кассир   
13                            NaN         NaN  Продавец-кассир   
...                           ...         ...              ...   
739675  Вывести из черного списка         NaN  Продавец-кассир   
739676  Вывести из черного списка         NaN  Продавец-кассир   
739678  Вывести из черного списка         NaN  Продавец-кассир   
739679  Вывести из черного списка         NaN  Продавец-кассир   
739680  Вывести из черного списка         NaN  Продавец-кассир   

        is_active_action  is_open_action  
0                   True           False  
3                   True           False  
4                   True           False  
11                  True           False  
13                  True           False  
...                  ...             ...  
739675              True            True  
739676              True            True  
739678              True            True  
739679              True            True  
739680              True            True  

[520487 rows x 11 columns]

In [16]:
df.columns

Index(['id_applicant', 'id_partner', 'id_log', 'department_id', 'action_date',
       'stage_name', 'activity_name', 'result_name', 'is_active_action',
       'is_open_action'],
      dtype='object')

In [59]:
df = df.drop(['position_name'], axis =1)

In [61]:
df['is_active_action'].value_counts()

True    520487
Name: is_active_action, dtype: int64

In [62]:
#Понятия не имею нахера тут столбец is_active_action если у него все значения тру
df = df.drop(['is_active_action'], axis =1)

In [65]:
df = df.sort_values(by = ['id_applicant', 'action_date']) #отсортируем данные по кандидату и дате действия 
df

id_applicant  id_partner    id_log  department_id  \
141051       4461761     3666193        -1          48941   
131357       4461766      939413        -1          45528   
89639        4461768     3666195        -1          17179   
104509       4461773     3666202        -1          48935   
106577       4461774      666213        -1          48834   
...              ...         ...       ...            ...   
448347       4886615     1040329  27106030          27473   
448348       4886615     1040329  27106031          27473   
448349       4886615     1040329  27106032          27473   
448350       4886615     1040329  27106033          27473   
448342       4886615     1040329  27106034          27473   

                          action_date          stage_name  \
141051  2020-01-03 08:03:40.219194+00  Создание кандидата   
131357  2020-01-03 08:07:37.207249+00  Создание кандидата   
89639   2020-01-03 08:09:56.331841+00  Создание кандидата   
104509  2020-01-03 08:14:27.343217+00  Создание кандидата   
106577  2020-01-03 08:15:05.173052+00  Создание кандидата   
...                               ...                 ...   
448347  2020-04-14 11:09:14.324975+00                  СБ   
448348  2020-04-14 11:09:15.338565+00                  СБ   
448349  2020-04-14 11:09:16.725966+00                  СБ   
448350  2020-04-14 11:09:18.335061+00          Оформление   
448342   2020-04-14 11:09:23.49207+00          Оформление   

                        activity_name      result_name  is_open_action  
141051                            NaN              NaN           False  
131357                            NaN              NaN           False  
89639                             NaN              NaN           False  
104509                            NaN              NaN           False  
106577                            NaN              NaN           False  
...                               ...              ...             ...  
448347   Подготовить анкету кандидата     Подготовлена           False  
448348           Узнать результаты СБ         Подходит           False  
448349       Проверка формы обращения        Не резерв           False  
448350  Назначить время на оформление  Время назначено           False  
448342       Узнать результаты приема           Принят           False  

[520487 rows x 9 columns]

In [66]:
df['is_open_action'].value_counts()

False    497094
True      23393
Name: is_open_action, dtype: int64

In [21]:
df['stage_name'].unique()

array(['Создание кандидата', 'Интервью с руководителем', 'Обработка',
       'Оформление', 'Смена вакансии', 'СБ', 'Не прошел СБ',
       'Мы отказали', 'Выход на работу', 'Отказался', 'Резерв',
       'Черный список'], dtype=object)

In [39]:
a = (['Создание кандидата', 'Интервью с руководителем', 'СБ', #Список стадий 2018
       'Обработка', 'Назначение времени на оформление/медосмотр',
       'Оформление', 'Смена вакансии', 'Выход на работу', 'Отказался',
       'Резерв', 'Ожидание', 'Не прошел СБ', 'Мы отказали',
       'Черный список', 'Кадровый резерв'])

In [40]:
b = (['Создание кандидата', 'Интервью с руководителем', 'Обработка', #список стадий 2020
       'Оформление', 'Смена вакансии', 'СБ', 'Не прошел СБ',
       'Мы отказали', 'Выход на работу', 'Отказался', 'Резерв',
       'Черный список'])

In [49]:
print('стадии что не вошли в 2020')
print('--------------')
i = 0
while i < 15:
    if (a[i] not in b):  
        print(a[i])
    i = i + 1

стадии что не вошли в 2018
--------------
Назначение времени на оформление/медосмотр
Ожидание
Кадровый резерв


In [67]:
print('стадии который нет в 2018, но есть в 2020')
print('--------------')
i = 0
while i < 12:
    if (b[i] not in a):  
        print(b[i])
    i = i + 1

стадии который нет в 2018, но есть в 2020
--------------


In [72]:
sorted_df['result_name'].value_counts()

Подходит                              77596
Не резерв                             59797
Встреча назначена                     44395
Недозвон                              34221
ОС не предоставлена руководителем     27677
Подготовлена                          17763
Отказ кандидата                       12811
Время назначено                       12255
Перенос звонка                        11939
Не подходит                           10163
Принят                                 7043
Нет обратной связи от руководителя     6053
Резерв                                 3771
ОС предоставлена руководителем         3319
Перенос кандидата                      3188
Отказ руководителя                     2786
В белый список                         2381
Нет обратной связи                      339
Не принят                                71
Перенос руководителя                     25
Уточнение данных                         22
Черный список                            13
Name: result_name, dtype: int64

In [86]:
sorted_df['stage_name'].value_counts()

Создание кандидата          149735
Интервью с руководителем    121372
Обработка                    99397
Оформление                   80919
СБ                           51537
Смена вакансии                9736
Не прошел СБ                  7666
Черный список                   54
Отказался                       43
Выход на работу                 19
Мы отказали                      7
Резерв                           2
Name: stage_name, dtype: int64

In [81]:
df[df['result_name'] == 'Принят']

id_applicant  id_partner    id_log  department_id  \
610929       4554398     3712663  26634580          34016   
348409       4578838     3732215  26847382          31117   
287517       4579888     2776525  26846233          31475   
267833       4592572     2542953  26895620          12874   
505104       4594868     3275293  26795536          36541   
...              ...         ...       ...            ...   
500827       4886560     1197774  27105784          35106   
615551       4886575     1542748  27105875          28162   
222109       4886579     3878216  27105890          10530   
680430       4886599     3884467  27105976          48259   
448342       4886615     1040329  27106034          27473   

                          action_date  stage_name             activity_name  \
610929  2020-03-25 16:13:10.972458+00  Оформление  Узнать результаты приема   
348409  2020-04-03 17:06:12.138947+00  Оформление  Узнать результаты приема   
287517  2020-04-03 16:40:06.073256+00  Оформление  Узнать результаты приема   
267833   2020-04-06 15:12:24.23083+00  Оформление  Узнать результаты приема   
505104  2020-04-01 16:07:24.806352+00  Оформление  Узнать результаты приема   
...                               ...         ...                       ...   
500827  2020-04-14 11:04:44.553692+00  Оформление  Узнать результаты приема   
615551  2020-04-14 11:06:42.313671+00  Оформление  Узнать результаты приема   
222109  2020-04-14 11:07:06.756809+00  Оформление  Узнать результаты приема   
680430  2020-04-14 11:08:17.306195+00  Оформление  Узнать результаты приема   
448342   2020-04-14 11:09:23.49207+00  Оформление  Узнать результаты приема   

       result_name  is_open_action  
610929      Принят           False  
348409      Принят           False  
287517      Принят           False  
267833      Принят           False  
505104      Принят           False  
...            ...             ...  
500827      Принят           False  
615551      Принят           False  
222109      Принят           False  
680430      Принят           False  
448342      Принят           False  

[7043 rows x 9 columns]

In [84]:
df[df['id_applicant'] == 4886560]

id_applicant  id_partner    id_log  department_id  \
185527       4886560     1197774        -1          35106   
500828       4886560     1197774  27105772          35106   
500829       4886560     1197774  27105774          35106   
500830       4886560     1197774  27105775          35106   
500831       4886560     1197774  27105777          35106   
500832       4886560     1197774  27105778          35106   
500833       4886560     1197774  27105779          35106   
500834       4886560     1197774  27105781          35106   
500835       4886560     1197774  27105783          35106   
500827       4886560     1197774  27105784          35106   

                          action_date                stage_name  \
185527  2020-04-14 11:04:14.792897+00        Создание кандидата   
500828  2020-04-14 11:04:31.540786+00                 Обработка   
500829  2020-04-14 11:04:32.775293+00                 Обработка   
500830  2020-04-14 11:04:34.239576+00  Интервью с руководителем   
500831   2020-04-14 11:04:35.44268+00  Интервью с руководителем   
500832  2020-04-14 11:04:36.590168+00                        СБ   
500833  2020-04-14 11:04:37.511006+00                        СБ   
500834  2020-04-14 11:04:38.764145+00                        СБ   
500835  2020-04-14 11:04:40.266221+00                Оформление   
500827  2020-04-14 11:04:44.553692+00                Оформление   

                                     activity_name        result_name  \
185527                                         NaN                NaN   
500828                Провести первичную обработку           Подходит   
500829                    Проверка формы обращения          Не резерв   
500830          Назначить интервью с руководителем  Встреча назначена   
500831  Узнать результаты интервью с руководителем           Подходит   
500832                Подготовить анкету кандидата       Подготовлена   
500833                        Узнать результаты СБ           Подходит   
500834                    Проверка формы обращения          Не резерв   
500835               Назначить время на оформление    Время назначено   
500827                    Узнать результаты приема             Принят   

        is_open_action  
185527           False  
500828           False  
500829           False  
500830           False  
500831           False  
500832           False  
500833           False  
500834           False  
500835           False  
500827           False

In [85]:
df[df['id_applicant'] == 4578838]

id_applicant  id_partner    id_log  department_id  \
63269        4578838     3732215        -1          31117   
348409       4578838     3732215  26847382          31117   

                          action_date          stage_name  \
63269   2020-01-31 16:15:32.064187+00  Создание кандидата   
348409  2020-04-03 17:06:12.138947+00          Оформление   

                   activity_name result_name  is_open_action  
63269                        NaN         NaN           False  
348409  Узнать результаты приема      Принят           False

In [114]:
df[df['result_name'] == 'Не подходит']

id_applicant  id_partner    id_log  department_id  \
624565       4508429     3693272  24806225          45475   
687761       4521022     3700455  24883201          45475   
510633       4522393     3701252  24891584          45475   
449710       4525247     3702867  24909505          45475   
525463       4552817     3718228  25071011          45475   
...              ...         ...       ...            ...   
481113       4886580     3818133  27105887           9623   
485610       4886582     1584354  27105896          32479   
402123       4886602     3221786  27105987          31560   
667835       4886609     3897218  27106004           8783   
473504       4886610     3897231  27106006          30523   

                          action_date stage_name  \
624565  2020-01-16 19:40:28.031985+00  Обработка   
687761   2020-01-20 15:39:24.50778+00  Обработка   
510633  2020-01-20 19:20:14.574291+00  Обработка   
449710  2020-01-21 12:48:23.334904+00  Обработка   
525463  2020-01-27 14:23:13.306976+00  Обработка   
...                               ...        ...   
481113  2020-04-14 11:06:58.866494+00  Обработка   
485610  2020-04-14 11:07:13.658676+00  Обработка   
402123  2020-04-14 11:08:33.963289+00  Обработка   
667835  2020-04-14 11:08:55.302545+00  Обработка   
473504  2020-04-14 11:08:56.884943+00  Обработка   

                       activity_name  result_name  is_open_action  
624565  Провести первичную обработку  Не подходит           False  
687761  Провести первичную обработку  Не подходит           False  
510633  Провести первичную обработку  Не подходит           False  
449710  Провести первичную обработку  Не подходит           False  
525463  Провести первичную обработку  Не подходит           False  
...                              ...          ...             ...  
481113  Провести первичную обработку  Не подходит           False  
485610  Провести первичную обработку  Не подходит           False  
402123  Провести первичную обработку  Не подходит           False  
667835  Провести первичную обработку  Не подходит           False  
473504  Провести первичную обработку  Не подходит           False  

[10163 rows x 9 columns]

In [115]:
df[df['id_applicant'] == 4508429]

id_applicant  id_partner    id_log  department_id  \
114971       4508429     3693272        -1          45475   
624565       4508429     3693272  24806225          45475   

                          action_date          stage_name  \
114971  2020-01-16 19:40:05.842549+00  Создание кандидата   
624565  2020-01-16 19:40:28.031985+00           Обработка   

                       activity_name  result_name  is_open_action  
114971                           NaN          NaN           False  
624565  Провести первичную обработку  Не подходит           False

In [116]:
df[df['result_name'] == 'Отказ руководителя']

id_applicant  id_partner    id_log  department_id  \
504810       4596351     3742207  26915963          47657   
447173       4604049     3746418  26733983           8953   
531767       4606578     3732088  26682531          48856   
275979       4636817     3764045  26753468          33606   
463764       4642430     3701662  26891901          32246   
...              ...         ...       ...            ...   
394267       4869762     3043427  27067309          12463   
244876       4870208     1992500  27067325          30345   
680168       4872356     3880330  27089224          31632   
325402       4872427     3879654  27089227           9569   
625338       4874098     2637019  27100503           9517   

                          action_date                stage_name  \
504810  2020-04-07 11:07:37.924276+00                Оформление   
447173  2020-03-30 14:03:29.903009+00                Оформление   
531767  2020-03-27 10:02:26.555663+00                Оформление   
275979  2020-03-31 10:04:00.939747+00                Оформление   
463764  2020-04-06 14:02:48.874113+00                Оформление   
...                               ...                       ...   
394267   2020-04-13 07:59:31.11027+00  Интервью с руководителем   
244876  2020-04-13 07:59:47.570114+00  Интервью с руководителем   
680168  2020-04-13 16:00:01.091958+00  Интервью с руководителем   
325402  2020-04-13 16:00:03.534783+00  Интервью с руководителем   
625338   2020-04-14 08:59:29.79655+00  Интервью с руководителем   

                                   activity_name         result_name  \
504810  Предоставить обратную связь по кандидату  Отказ руководителя   
447173  Предоставить обратную связь по кандидату  Отказ руководителя   
531767  Предоставить обратную связь по кандидату  Отказ руководителя   
275979  Предоставить обратную связь по кандидату  Отказ руководителя   
463764  Предоставить обратную связь по кандидату  Отказ руководителя   
...                                          ...                 ...   
394267  Предоставить обратную связь по кандидату  Отказ руководителя   
244876  Предоставить обратную связь по кандидату  Отказ руководителя   
680168  Предоставить обратную связь по кандидату  Отказ руководителя   
325402  Предоставить обратную связь по кандидату  Отказ руководителя   
625338  Предоставить обратную связь по кандидату  Отказ руководителя   

        is_open_action  
504810           False  
447173           False  
531767           False  
275979           False  
463764           False  
...                ...  
394267           False  
244876           False  
680168           False  
325402           False  
625338           False  

[2786 rows x 9 columns]

In [117]:
df[df['id_applicant'] == 4604049]

id_applicant  id_partner    id_log  department_id  \
84442        4604049     3746418        -1           8953   
447177       4604049     3746418  26648999           8953   
447176       4604049     3746418  26677886           8953   
447175       4604049     3746418  26701790           8953   
447174       4604049     3746418  26733981           8953   
447173       4604049     3746418  26733983           8953   

                          action_date          stage_name  \
84442   2020-02-06 13:58:12.394886+00  Создание кандидата   
447177  2020-03-26 10:02:45.221678+00          Оформление   
447176  2020-03-27 08:02:07.228079+00          Оформление   
447175  2020-03-27 16:02:35.947153+00          Оформление   
447174   2020-03-30 14:03:29.21226+00          Оформление   
447173  2020-03-30 14:03:29.903009+00          Оформление   

                                   activity_name  \
84442                                        NaN   
447177  Предоставить обратную связь по кандидату   
447176  Предоставить обратную связь по кандидату   
447175  Предоставить обратную связь по кандидату   
447174  Предоставить обратную связь по кандидату   
447173  Предоставить обратную связь по кандидату   

                              result_name  is_open_action  
84442                                 NaN           False  
447177  ОС не предоставлена руководителем           False  
447176  ОС не предоставлена руководителем           False  
447175  ОС не предоставлена руководителем           False  
447174  ОС не предоставлена руководителем           False  
447173                 Отказ руководителя           False

In [118]:
df[df['result_name'] == 'Черный список']

id_applicant  id_partner    id_log  department_id  \
513560       4758392     3197557  26669264          10708   
464338       4760133     3605084  26672709          25514   
587253       4790505     3844094  26676767          47391   
249563       4801774      783604  26772145           7692   
570626       4814273     3516801  26839326          36545   
457005       4821320     3856217  26756980          33730   
337014       4822333     3824380  26927895           7947   
359958       4829525     3864281  26925976          11890   
509602       4832169     3290102  26878940          11755   
234022       4833808     3759937  27005858          32606   
463885       4838320     3869749  26832844          49734   
248999       4838801     3870090  26846214           8007   
422775       4847557     3873113  26951875          11448   

                          action_date                stage_name  \
513560  2020-03-26 15:51:42.035459+00                Оформление   
464338  2020-03-26 16:40:37.178679+00               Мы отказали   
587253  2020-03-26 18:25:24.145281+00                Оформление   
249563  2020-03-31 16:02:47.311494+00                Оформление   
570626  2020-04-03 14:19:51.211505+00                Оформление   
457005   2020-03-31 11:03:38.56883+00                Оформление   
337014  2020-04-07 14:30:54.276778+00                Оформление   
359958  2020-04-07 13:54:16.351718+00                Оформление   
509602  2020-04-06 09:20:17.195593+00  Интервью с руководителем   
234022  2020-04-09 18:09:54.040015+00  Интервью с руководителем   
463885  2020-04-03 11:49:55.127966+00  Интервью с руководителем   
248999  2020-04-03 16:39:43.313767+00                Оформление   
422775  2020-04-08 11:41:16.260562+00  Интервью с руководителем   

                                     activity_name    result_name  \
513560               Назначить время на оформление  Черный список   
464338                                         NaN  Черный список   
587253    Предоставить обратную связь по кандидату  Черный список   
249563                    Узнать результаты приема  Черный список   
570626                    Узнать результаты приема  Черный список   
457005               Назначить время на оформление  Черный список   
337014                    Узнать результаты приема  Черный список   
359958               Назначить время на оформление  Черный список   
509602  Узнать результаты интервью с руководителем  Черный список   
234022  Узнать результаты интервью с руководителем  Черный список   
463885  Узнать результаты интервью с руководителем  Черный список   
248999               Назначить время на оформление  Черный список   
422775  Узнать результаты интервью с руководителем  Черный список   

        is_open_action  
513560           False  
464338           False  
587253           False  
249563           False  
570626           False  
457005           False  
337014           False  
359958           False  
509602           False  
234022           False  
463885           False  
248999           False  
422775           False

In [120]:
df[df['id_applicant'] == 4790505]

id_applicant  id_partner    id_log  department_id  \
164238       4790505     3844094        -1          47391   
587254       4790505     3844094  26653216          47391   
587253       4790505     3844094  26676767          47391   
726136       4790505     3844094        -1          47391   

                          action_date          stage_name  \
164238  2020-03-22 09:25:42.950146+00  Создание кандидата   
587254   2020-03-26 11:02:40.40499+00          Оформление   
587253  2020-03-26 18:25:24.145281+00          Оформление   
726136   2020-04-23 16:26:11.80918+00       Черный список   

                                   activity_name  \
164238                                       NaN   
587254  Предоставить обратную связь по кандидату   
587253  Предоставить обратную связь по кандидату   
726136                 Вывести из черного списка   

                              result_name  is_open_action  
164238                                NaN           False  
587254  ОС не предоставлена руководителем           False  
587253                      Черный список           False  
726136                                NaN            True

Классно получается, у нас стадии этапы найма одного человека записываются полность, а другого заносят в систему только на создание и оформление, данные не все ---> Система не проверяет предыдущие этапы и даёт запись сразу на последний этап(подразумеваю что так не должно работать)

1) Стадия 'Создание кандидата'

Полный аналог 2018

In [87]:
le_masque = df['stage_name'] == 'Создание кандидата'
df_create = df[le_masque]
df_create['activity_name'].unique()

array([nan], dtype=object)

2) Стадия 'Обработак' 

Обратить внимание, что у Ани 6 активностей на обработку, а в 2020 только две

Да и разновидности вариантов активностей в 2018 году было больше

In [89]:
le_masque = df['stage_name'] == 'Обработка'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

array(['Провести первичную обработку', 'Проверка формы обращения'],
      dtype=object)

In [90]:
le_masque = df['stage_name'] == 'Обработка'
le_masque &= df['activity_name'] == 'Провести первичную обработку'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

array(['Подходит', 'Не подходит', 'Отказ кандидата', 'Перенос звонка',
       'Недозвон', nan, 'Резерв'], dtype=object)

In [91]:
le_masque = df['stage_name'] == 'Обработка'
le_masque &= df['activity_name'] == 'Проверка формы обращения'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

array(['Не резерв', 'Подходит'], dtype=object)

3) 'Интервью с руководителем'

Полный аналог активнойстей с 2018

Но по разновидностям вариантов активностей снова меньше чем в 2018

In [92]:
le_masque = df['stage_name'] == 'Интервью с руководителем'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

array(['Назначить интервью с руководителем',
       'Узнать результаты интервью с руководителем',
       'Предоставить обратную связь по кандидату'], dtype=object)

In [93]:
le_masque = df['stage_name'] == 'Интервью с руководителем'
le_masque &= df['activity_name'] == 'Назначить интервью с руководителем'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

array(['Встреча назначена', 'Отказ кандидата', 'Перенос звонка',
       'Недозвон', 'Резерв', nan, 'Не подходит', 'Подходит',
       'Перенос кандидата'], dtype=object)

In [94]:
le_masque = df['stage_name'] == 'Интервью с руководителем'
le_masque &= df['activity_name'] == 'Узнать результаты интервью с руководителем'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

array(['Перенос звонка', 'Недозвон', 'Подходит', nan, 'Отказ кандидата',
       'Нет обратной связи от руководителя', 'Резерв',
       'Перенос кандидата', 'Не подходит', 'Встреча назначена',
       'Перенос руководителя', 'ОС предоставлена руководителем',
       'Черный список'], dtype=object)

In [95]:
le_masque = df['stage_name'] == 'Интервью с руководителем'
le_masque &= df['activity_name'] == 'Предоставить обратную связь по кандидату'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

array(['ОС не предоставлена руководителем',
       'ОС предоставлена руководителем', 'Отказ руководителя',
       'Встреча назначена', nan, 'Нет обратной связи от руководителя',
       'Не подходит', 'Подходит', 'Недозвон'], dtype=object)

4) Оформление

In [96]:
le_masque = df['stage_name'] == 'Оформление'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

array(['Назначить время на оформление', 'Узнать результаты приема',
       'Предоставить обратную связь по кандидату'], dtype=object)

In [97]:
le_masque = df['stage_name'] == 'Оформление'
le_masque &= df['activity_name'] == 'Назначить время на оформление'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

array(['Недозвон', 'Резерв', 'Время назначено', 'Перенос звонка', nan,
       'Отказ кандидата', 'Черный список', 'Перенос кандидата',
       'Встреча назначена', 'Не подходит'], dtype=object)

In [98]:
le_masque = df['stage_name'] == 'Оформление'
le_masque &= df['activity_name'] == 'Узнать результаты приема'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

array(['Принят', 'Недозвон', nan, 'Перенос кандидата',
       'Нет обратной связи от руководителя', 'Перенос звонка',
       'Отказ кандидата', 'Резерв', 'Не принят', 'Перенос руководителя',
       'ОС предоставлена руководителем', 'Черный список',
       'Время назначено'], dtype=object)

In [99]:
le_masque = df['stage_name'] == 'Оформление'
le_masque &= df['activity_name'] == 'Предоставить обратную связь по кандидату'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

array(['ОС не предоставлена руководителем',
       'ОС предоставлена руководителем', 'Отказ руководителя', nan,
       'Время назначено', 'Черный список', 'Перенос звонка',
       'Нет обратной связи от руководителя', 'Недозвон'], dtype=object)

5) СБ 

Активностей в 2018 снова больше

In [100]:
le_masque = df['stage_name'] == 'СБ'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

array(['Подготовить анкету кандидата', 'Узнать результаты СБ',
       'Проверка формы обращения'], dtype=object)

In [101]:
le_masque = df['stage_name'] == 'СБ'
le_masque &= df['activity_name'] == 'Подготовить анкету кандидата'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

array([nan, 'Подготовлена'], dtype=object)

In [102]:
le_masque = df['stage_name'] == 'СБ'
le_masque &= df['activity_name'] == 'Узнать результаты СБ'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

array(['Подходит', nan, 'Подготовлена', 'Нет обратной связи',
       'Не подходит', 'Нет обратной связи от руководителя',
       'Уточнение данных', 'Недозвон'], dtype=object)

In [103]:
le_masque = df['stage_name'] == 'СБ'
le_masque &= df['activity_name'] == 'Проверка формы обращения'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

array(['Не резерв', 'Подготовлена'], dtype=object)

6)Смена вакансии  

Ну хоть где-то аналог с 2018 XD

In [104]:
le_masque = df['stage_name'] == 'Смена вакансии'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

array([nan], dtype=object)

7)Не прошел СБ 

In [105]:
le_masque = df['stage_name'] == 'Не прошел СБ'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

array(['Вывести из черного списка'], dtype=object)

In [106]:
le_masque = df['stage_name'] == 'Не прошел СБ'
le_masque &= df['activity_name'] == 'Вывести из черного списка'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

array(['В белый список', nan], dtype=object)

8)Черный список

в 2018 на действие вывести из черного списка, есть 'в белый список'

In [107]:
le_masque = df['stage_name'] == 'Черный список'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

array(['Вывести из черного списка'], dtype=object)

In [108]:
le_masque = df['stage_name'] == 'Черный список'
le_masque &= df['activity_name'] == 'Вывести из черного списка'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

array([nan], dtype=object)

9)Отказался

In [109]:
le_masque = df['stage_name'] == 'Отказался'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

array([nan], dtype=object)

10)Выход на работу

In [110]:
le_masque = df['stage_name'] == 'Выход на работу'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

array([nan], dtype=object)

11)Мы отказали

In [111]:
le_masque = df['stage_name'] == 'Мы отказали'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

array([nan], dtype=object)

12)Резерв

In [113]:
le_masque = df['stage_name'] == 'Резерв'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

array([nan], dtype=object)