# Данные за 2018 год

In [3]:
import pandas as pd
import numpy as np

# Загружаем наш датасет с исходными данными
data = pd.read_csv("C:\\Users\\anna.nazarova\\Desktop\\Мага\\НИР\\with_closed_ations_as________select_app_2018_X5_STORES.csv")
data

id_applicant  id_partner  id_log  department_id  \
0             3080432     2883423      -1           9044   
1             2873477     2761171      -1          32087   
2             2896621     2776555      -1          32087   
3             2906437     2782282      -1          32087   
4             2965200     2816229      -1          32087   
...               ...         ...     ...            ...   
7211284       3221933     2968967      -1          25660   
7211285       3007369     2840731      -1          10687   
7211286       3230514     2974049      -1          10718   
7211287       3117018     2905192      -1          10718   
7211288       2581506     2596820      -1          10718   

                           action_date  \
0         2018-10-16 18:11:10.00318+00   
1        2018-08-15 10:36:32.936322+00   
2        2018-08-22 14:09:27.083354+00   
3        2018-08-24 15:55:27.912704+00   
4        2018-09-11 15:00:49.242929+00   
...                                ...   
7211284  2020-04-23 15:05:45.859137+00   
7211285  2020-04-23 15:05:45.859137+00   
7211286  2020-04-23 15:05:45.859137+00   
7211287  2020-04-23 15:05:45.859137+00   
7211288  2020-04-23 15:05:45.859137+00   

                                         stage_name  \
0                                Создание кандидата   
1                                Создание кандидата   
2                                Создание кандидата   
3                                Создание кандидата   
4                                Создание кандидата   
...                                             ...   
7211284                    Интервью с руководителем   
7211285                                  Оформление   
7211286                                  Оформление   
7211287  Назначение времени на оформление/медосмотр   
7211288                                    Ожидание   

                                             activity_name result_name  \
0                                                      NaN         NaN   
1                                                      NaN         NaN   
2                                                      NaN         NaN   
3                                                      NaN         NaN   
4                                                      NaN         NaN   
...                                                    ...         ...   
7211284         Узнать результаты интервью с руководителем         NaN   
7211285                           Узнать результаты приема         NaN   
7211286                           Узнать результаты приема         NaN   
7211287  Назначить время на оформление/медосмотр (недоз...         NaN   
7211288                                  Вернуть в воронку         NaN   

           position_name  is_active_action  is_open_action  
0        Продавец-кассир              True           False  
1        Продавец-кассир              True           False  
2        Продавец-кассир              True           False  
3        Продавец-кассир              True           False  
4        Продавец-кассир              True           False  
...                  ...               ...             ...  
7211284  Продавец-кассир              True            True  
7211285  Продавец-кассир              True            True  
7211286  Продавец-кассир              True            True  
7211287  Продавец-кассир              True            True  
7211288  Продавец-кассир              True            True  

[7211289 rows x 11 columns]

Нас интересует найм только продавцов-кассиров. Кроме того,оставим для анализа только активные действия:

In [4]:
le_masque = data['position_name'] == 'Продавец-кассир'
le_masque &= data['is_active_action'] == True
df_seller = data[le_masque]
df_seller

id_applicant  id_partner  id_log  department_id  \
0             3080432     2883423      -1           9044   
1             2873477     2761171      -1          32087   
2             2896621     2776555      -1          32087   
3             2906437     2782282      -1          32087   
4             2965200     2816229      -1          32087   
...               ...         ...     ...            ...   
7211284       3221933     2968967      -1          25660   
7211285       3007369     2840731      -1          10687   
7211286       3230514     2974049      -1          10718   
7211287       3117018     2905192      -1          10718   
7211288       2581506     2596820      -1          10718   

                           action_date  \
0         2018-10-16 18:11:10.00318+00   
1        2018-08-15 10:36:32.936322+00   
2        2018-08-22 14:09:27.083354+00   
3        2018-08-24 15:55:27.912704+00   
4        2018-09-11 15:00:49.242929+00   
...                                ...   
7211284  2020-04-23 15:05:45.859137+00   
7211285  2020-04-23 15:05:45.859137+00   
7211286  2020-04-23 15:05:45.859137+00   
7211287  2020-04-23 15:05:45.859137+00   
7211288  2020-04-23 15:05:45.859137+00   

                                         stage_name  \
0                                Создание кандидата   
1                                Создание кандидата   
2                                Создание кандидата   
3                                Создание кандидата   
4                                Создание кандидата   
...                                             ...   
7211284                    Интервью с руководителем   
7211285                                  Оформление   
7211286                                  Оформление   
7211287  Назначение времени на оформление/медосмотр   
7211288                                    Ожидание   

                                             activity_name result_name  \
0                                                      NaN         NaN   
1                                                      NaN         NaN   
2                                                      NaN         NaN   
3                                                      NaN         NaN   
4                                                      NaN         NaN   
...                                                    ...         ...   
7211284         Узнать результаты интервью с руководителем         NaN   
7211285                           Узнать результаты приема         NaN   
7211286                           Узнать результаты приема         NaN   
7211287  Назначить время на оформление/медосмотр (недоз...         NaN   
7211288                                  Вернуть в воронку         NaN   

           position_name  is_active_action  is_open_action  
0        Продавец-кассир              True           False  
1        Продавец-кассир              True           False  
2        Продавец-кассир              True           False  
3        Продавец-кассир              True           False  
4        Продавец-кассир              True           False  
...                  ...               ...             ...  
7211284  Продавец-кассир              True            True  
7211285  Продавец-кассир              True            True  
7211286  Продавец-кассир              True            True  
7211287  Продавец-кассир              True            True  
7211288  Продавец-кассир              True            True  

[5587055 rows x 11 columns]

In [11]:
df_seller.columns #названия колонок

Index(['id_applicant', 'id_partner', 'id_log', 'department_id', 'action_date',
       'stage_name', 'activity_name', 'result_name', 'position_name',
       'is_active_action', 'is_open_action'],
      dtype='object')

Предполагаю, что колонки отражают следующую информацию:
###### 1) идентификатор кандидата;
###### 2) идентификатор партнера (думаю, речь о компании, в которую мы побираем кандидата - 5-ка и т.д.);
###### 3) идентификатор чего-то (для одного кандидата один такой индификатор вне зависимости от стадии/активности);
###### 4) дата и время действия со стороны компании; 
###### 5) наименование стадии процесса найма;
###### 6) наименование активности внутри этой стадии;
###### 7) результат активности п.6;
###### 8) наименование должности (можем удалить, оставили только продавцов-кассиром по условию);
###### 9) флаг актуальности действия (можем удалить, оставили только актуальные записи)
###### 10) открыто ли действие на данный момент    

In [15]:
sorted_df = df_seller.sort_values(by = ['id_applicant', 'action_date']) #отсортируем данные по кандидату и дате действия 
sorted_df = sorted_df.drop(['position_name', 'is_active_action'], axis =1)
sorted_df

id_applicant  id_partner    id_log  department_id  \
1090921       2196745     2281753        -1          25165   
6407648       2196745     2281753  10890124          25165   
6407647       2196745     2281753  10890125          25165   
6407646       2196745     2281753  10890126          25165   
6407642       2196745     2281753  11280536          25165   
...               ...         ...       ...            ...   
3376830       3330735     1970383  17153319          32843   
3376829       3330735     1970383  17153320          32843   
3376828       3330735     1970383  17231319          32843   
3376827       3330735     1970383  17279875          32843   
3376824       3330735     1970383  17394979          32843   

                           action_date                stage_name  \
1090921  2018-01-05 06:20:57.274499+00        Создание кандидата   
6407648  2018-01-05 06:21:16.616158+00  Интервью с руководителем   
6407647  2018-01-05 06:21:17.145886+00  Интервью с руководителем   
6407646  2018-01-05 06:21:17.616696+00                        СБ   
6407642  2018-01-29 15:43:47.354909+00                 Обработка   
...                                ...                       ...   
3376830  2018-12-29 19:25:47.832687+00                 Обработка   
3376829  2018-12-29 19:25:58.002618+00  Интервью с руководителем   
3376828  2019-01-11 12:26:29.466622+00  Интервью с руководителем   
3376827  2019-01-15 09:19:37.355139+00  Интервью с руководителем   
3376824         2019-01-21 09:51:38+00            Смена вакансии   

                                      activity_name         result_name  \
1090921                                         NaN                 NaN   
6407648          Назначить интервью с руководителем   Встреча назначена   
6407647  Узнать результаты интервью с руководителем            Подходит   
6407646                Подготовить анкету кандидата        Подготовлена   
6407642                Провести первичную обработку            Подходит   
...                                             ...                 ...   
3376830                    Проверка формы обращения           Не резерв   
3376829          Назначить интервью с руководителем   Встреча назначена   
3376828  Узнать результаты интервью с руководителем  Нет обратной связи   
3376827  Узнать результаты интервью с руководителем  Нет обратной связи   
3376824                                         NaN                 NaN   

         is_open_action  
1090921           False  
6407648           False  
6407647           False  
6407646           False  
6407642           False  
...                 ...  
3376830           False  
3376829           False  
3376828           False  
3376827           False  
3376824           False  

[5587055 rows x 9 columns]

In [18]:
sorted_df['stage_name'].unique() # уникальные стадии найма

array(['Создание кандидата', 'Интервью с руководителем', 'СБ',
       'Обработка', 'Назначение времени на оформление/медосмотр',
       'Оформление', 'Смена вакансии', 'Выход на работу', 'Отказался',
       'Резерв', 'Ожидание', 'Не прошел СБ', 'Мы отказали',
       'Черный список', 'Кадровый резерв'], dtype=object)

Для каждой стадии хочу посмотреть активности и их результаты 

1) Стадия 'Создание кандидата'

In [21]:
le_masque = sorted_df['stage_name'] == 'Создание кандидата'
df_create = sorted_df[le_masque]
df_create['activity_name'].unique()

array([nan], dtype=object)

2) Стадия 'Интервью с руководителем'

In [22]:
le_masque = sorted_df['stage_name'] == 'Интервью с руководителем'
df_inter = sorted_df[le_masque]
df_inter['activity_name'].unique()

array(['Назначить интервью с руководителем',
       'Узнать результаты интервью с руководителем',
       'Подготовить анкету кандидата'], dtype=object)

In [24]:
le_masque = sorted_df['stage_name'] == 'Интервью с руководителем'
le_masque &= sorted_df['activity_name'] == 'Назначить интервью с руководителем'
df_inter_2 = sorted_df[le_masque]
df_inter_2['result_name'].unique()

array(['Встреча назначена', 'Резерв', 'Отказ кандидата',
       'Нет обратной связи', 'Отказ руководителя', 'Подходит', nan,
       'Перенос звонка', 'Ожидание', 'Недозвон', 'Перенос кандидата',
       'Интервью с руководителем', 'Не подходит', 'Обработка', 'Принят'],
      dtype=object)

In [25]:
le_masque = sorted_df['stage_name'] == 'Интервью с руководителем'
le_masque &= sorted_df['activity_name'] == 'Узнать результаты интервью с руководителем'
df_inter_3 = sorted_df[le_masque]
df_inter_3['result_name'].unique()

array(['Подходит', 'Нет обратной связи', 'Отказ кандидата', 'Резерв',
       'Перенос кандидата', 'Не подходит', 'Встреча назначена',
       'Перенос руководителя', 'Недозвон', nan, 'Ожидание',
       'Перенос звонка', 'Интервью с руководителем', 'Черный список'],
      dtype=object)

In [26]:
le_masque = sorted_df['stage_name'] == 'Интервью с руководителем'
le_masque &= sorted_df['activity_name'] == 'Подготовить анкету кандидата'
df_inter_4 = sorted_df[le_masque]
df_inter_4['result_name'].unique()

array(['Подходит'], dtype=object)

3) Стадия 'СБ' -- служба безопасности

In [28]:
le_masque = sorted_df['stage_name'] == 'СБ'
df_sb = sorted_df[le_masque]
df_sb['activity_name'].unique()

array(['Подготовить анкету кандидата', 'Узнать результаты СБ',
       'Получить согласование повторного приема и отправить в СБ',
       'Проверка формы обращения'], dtype=object)

In [29]:
le_masque = sorted_df['stage_name'] == 'СБ'
le_masque &= sorted_df['activity_name'] == 'Подготовить анкету кандидата'
df_sb_2 = sorted_df[le_masque]
df_sb_2['result_name'].unique()

array(['Подготовлена', 'Отказ кандидата', 'Не подготовлена', 'Подходит',
       'Резерв', 'Встреча назначена', nan, 'СБ', 'Ожидание',
       'Нет обратной связи', 'Данные не предоставлены'], dtype=object)

In [30]:
le_masque = sorted_df['stage_name'] == 'СБ'
le_masque &= sorted_df['activity_name'] == 'Узнать результаты СБ'
df_sb_3 = sorted_df[le_masque]
df_sb_3['result_name'].unique()

array(['Подходит', 'Не подходит', 'Нет обратной связи',
       'Уточнение данных', 'Согласование повторного приема',
       'Подготовлена', 'Резерв', 'Встреча назначена', nan, 'Получено',
       'Недозвон', 'Перенос кандидата', 'Отказ кандидата', 'Ожидание',
       'Черный список'], dtype=object)

In [31]:
le_masque = sorted_df['stage_name'] == 'СБ'
le_masque &= sorted_df['activity_name'] == 'Получить согласование повторного приема и отправить в СБ'
df_sb_4 = sorted_df[le_masque]
df_sb_4['result_name'].unique()

array(['Не получено', 'Получено', 'Подготовлена', nan], dtype=object)

In [32]:
le_masque = sorted_df['stage_name'] == 'СБ'
le_masque &= sorted_df['activity_name'] == 'Проверка формы обращения'
df_sb_5 = sorted_df[le_masque]
df_sb_5['result_name'].unique()

array(['Не резерв', 'Подготовлена', 'Кадровый резерв'], dtype=object)

4) Стадия 'Обработка'

In [33]:
le_masque = sorted_df['stage_name'] == 'Обработка'
df_ob = sorted_df[le_masque]
df_ob['activity_name'].unique()

array(['Провести первичную обработку', 'Проверка формы обращения', nan,
       'Проверка источника', 'Узнать результаты медосмотра',
       'Узнать результаты СБ',
       'Назначить время на оформление/медосмотр (недозвон)'], dtype=object)

In [34]:
le_masque = sorted_df['stage_name'] == 'Обработка'
le_masque &= sorted_df['activity_name'] == 'Провести первичную обработку'
df_ob_2 = sorted_df[le_masque]
df_ob_2['result_name'].unique()

array(['Подходит', 'Недозвон', 'Отказ кандидата', 'Не подходит', 'Резерв',
       'Перенос звонка', 'Ожидание', nan, 'Встреча назначена',
       'Обработка', 'Интервью с руководителем',
       'Назначить время на оформление/медосмотр', 'Нет обратной связи',
       'Принят'], dtype=object)

In [35]:
le_masque = sorted_df['stage_name'] == 'Обработка'
le_masque &= sorted_df['activity_name'] == 'Проверка формы обращения'
df_ob_3 = sorted_df[le_masque]
df_ob_3['result_name'].unique()

array(['Не резерв', 'Подходит', 'Кадровый резерв'], dtype=object)

In [36]:
le_masque = sorted_df['stage_name'] == 'Обработка'
le_masque &= sorted_df['activity_name'] == 'Проверка источника'
df_ob_4 = sorted_df[le_masque]
df_ob_4['result_name'].unique()

array(['Источник не Яндекс Цифра', 'Источник Яндекс Цифра', 'Подходит',
       nan], dtype=object)

In [37]:
le_masque = sorted_df['stage_name'] == 'Обработка'
le_masque &= sorted_df['activity_name'] == 'Узнать результаты медосмотра'
df_ob_5 = sorted_df[le_masque]
df_ob_5['result_name'].unique()

array(['Недозвон'], dtype=object)

In [38]:
le_masque = sorted_df['stage_name'] == 'Обработка'
le_masque &= sorted_df['activity_name'] == 'Узнать результаты СБ'
df_ob_6 = sorted_df[le_masque]
df_ob_6['result_name'].unique()

array(['Подходит'], dtype=object)

In [39]:
le_masque = sorted_df['stage_name'] == 'Обработка'
le_masque &= sorted_df['activity_name'] == 'Назначить время на оформление/медосмотр (недозвон)'
df_ob_7 = sorted_df[le_masque]
df_ob_7['result_name'].unique()

array(['Недозвон'], dtype=object)

5) Стадия 'Назначение времени на оформление/медосмотр'

In [40]:
le_masque = sorted_df['stage_name'] == 'Назначение времени на оформление/медосмотр'
df_ob = sorted_df[le_masque]
df_ob['activity_name'].unique()

array(['Назначить время на оформление/медосмотр',
       'Назначить время на оформление/медосмотр (недозвон)',
       'Узнать результаты медосмотра'], dtype=object)

In [41]:
le_masque = sorted_df['stage_name'] == 'Назначение времени на оформление/медосмотр'
le_masque &= sorted_df['activity_name'] == 'Назначить время на оформление/медосмотр'
df_of = sorted_df[le_masque]
df_of['result_name'].unique()

array(['Время назначено', 'Недозвон', 'Отказ кандидата',
       'Направлен на медосмотр', 'Подходит', 'Резерв', 'Перенос звонка',
       'Нет обратной связи', 'Ожидание', 'Не подходит',
       'Назначить время на оформление/медосмотр', 'Принят',
       'Встреча назначена', 'В ожидании', 'Оформление'], dtype=object)

In [42]:
le_masque = sorted_df['stage_name'] == 'Назначение времени на оформление/медосмотр'
le_masque &= sorted_df['activity_name'] == 'Назначить время на оформление/медосмотр (недозвон)'
df_of_2 = sorted_df[le_masque]
df_of_2['result_name'].unique()

array(['Время назначено', 'Отказ кандидата', 'Направлен на медосмотр',
       'Недозвон', 'Резерв', 'Перенос звонка', 'Подходит', 'Ожидание',
       nan, 'СБ', 'Нет обратной связи', 'В ожидании', 'Черный список'],
      dtype=object)

In [43]:
le_masque = sorted_df['stage_name'] == 'Назначение времени на оформление/медосмотр'
le_masque &= sorted_df['activity_name'] == 'Узнать результаты медосмотра'
df_of_3 = sorted_df[le_masque]
df_of_3['result_name'].unique()

array(['Подходит', 'Время назначено', 'Недозвон', 'Отказ кандидата',
       'Резерв', 'Не подходит', 'Перенос звонка',
       'Направлен на медосмотр', 'Ожидание', nan, 'В ожидании'],
      dtype=object)

6) Стадия 'Оформление'

In [44]:
le_masque = sorted_df['stage_name'] == 'Оформление'
df_off = sorted_df[le_masque]
df_off['activity_name'].unique()

array(['Узнать результаты приема',
       'Назначить время на оформление/медосмотр',
       'Назначить время на оформление/медосмотр (недозвон)',
       'Назначить время на оформление', 'Узнать результаты медосмотра',
       nan], dtype=object)

In [45]:
le_masque = sorted_df['stage_name'] == 'Оформление'
le_masque &= sorted_df['activity_name'] == 'Узнать результаты приема'
df_off_2 = sorted_df[le_masque]
df_off_2['result_name'].unique()

array(['В ожидании', 'Принят', 'Отказ кандидата', 'Резерв', 'Не принят',
       nan, 'Недозвон', 'Подходит', 'Время назначено', 'Ожидание',
       'Оформление', 'Нет обратной связи', 'Направлен на медосмотр',
       'Встреча назначена', 'Черный список'], dtype=object)

In [46]:
le_masque = sorted_df['stage_name'] == 'Оформление'
le_masque &= sorted_df['activity_name'] == 'Назначить время на оформление/медосмотр'
df_off_3 = sorted_df[le_masque]
df_off_3['result_name'].unique()

array(['Недозвон', 'Время назначено', 'Ожидание',
       'Направлен на медосмотр', 'Отказ кандидата', 'Резерв', nan,
       'Подходит', 'Не подходит', 'Встреча назначена', 'Перенос звонка'],
      dtype=object)

In [47]:
le_masque = sorted_df['stage_name'] == 'Оформление'
le_masque &= sorted_df['activity_name'] == 'Назначить время на оформление/медосмотр (недозвон)'
df_off_4 = sorted_df[le_masque]
df_off_4['result_name'].unique()

array(['Недозвон', 'Отказ кандидата', 'Время назначено', nan, 'Резерв',
       'Ожидание'], dtype=object)

In [48]:
le_masque = sorted_df['stage_name'] == 'Оформление'
le_masque &= sorted_df['activity_name'] == 'Назначить время на оформление'
df_off_4 = sorted_df[le_masque]
df_off_4['result_name'].unique()

array(['Время назначено'], dtype=object)

In [49]:
le_masque = sorted_df['stage_name'] == 'Оформление'
le_masque &= sorted_df['activity_name'] == 'Узнать результаты медосмотра'
df_off_5 = sorted_df[le_masque]
df_off_5['result_name'].unique()

array(['Недозвон', 'Перенос звонка', 'Отказ кандидата', 'Подходит', nan,
       'Резерв', 'Ожидание', 'Время назначено'], dtype=object)

7) Стадия 'Смена вакансии'

In [51]:
le_masque = sorted_df['stage_name'] == 'Смена вакансии'
df_sm = sorted_df[le_masque]
df_sm['activity_name'].unique()

array([nan], dtype=object)

8) Стадия 'Выход на работу'

In [52]:
le_masque = sorted_df['stage_name'] == 'Выход на работу'
df_exit = sorted_df[le_masque]
df_exit['activity_name'].unique()

array([nan, 'Проверить выход на работу', 'Узнать результаты приема'],
      dtype=object)

In [53]:
le_masque = sorted_df['stage_name'] == 'Выход на работу'
le_masque &= sorted_df['activity_name'] == 'Проверить выход на работу'
df_exit_2 = sorted_df[le_masque]
df_exit_2['result_name'].unique()

array(['Вышел'], dtype=object)

In [54]:
le_masque = sorted_df['stage_name'] == 'Выход на работу'
le_masque &= sorted_df['activity_name'] == 'Узнать результаты приема'
df_exit_3 = sorted_df[le_masque]
df_exit_3['result_name'].unique()

array(['Принят'], dtype=object)

9) Стадия 'Отказался'

In [55]:
le_masque = sorted_df['stage_name'] == 'Отказался'
df_otk = sorted_df[le_masque]
df_otk['activity_name'].unique()

array([nan], dtype=object)

10) Стадия 'Резерв'

In [59]:
le_masque = sorted_df['stage_name'] == 'Резерв'
df_res = sorted_df[le_masque]
df_res['activity_name'].unique()

array([nan], dtype=object)

11) Стадия 'Ожидание'

In [60]:
le_masque = sorted_df['stage_name'] == 'Ожидание'
df_wait = sorted_df[le_masque]
df_wait['activity_name'].unique()

array(['Вернуть в воронку', 'Назначить интервью с руководителем',
       'Назначить время на оформление/медосмотр',
       'Провести первичную обработку', 'Узнать результаты приема', nan],
      dtype=object)

In [61]:
le_masque = sorted_df['stage_name'] == 'Ожидание'
le_masque &= sorted_df['activity_name'] == 'Вернуть в воронку'
df_wait_1 = sorted_df[le_masque]
df_wait_1['result_name'].unique()

array(['Назначить время на оформление/медосмотр', nan,
       'Интервью с руководителем', 'Оформление', 'Обработка', 'Подходит',
       'СБ', 'Недозвон', 'Ожидание', 'Нет обратной связи', 'В ожидании',
       'Время назначено', 'Не подходит'], dtype=object)

In [62]:
le_masque = sorted_df['stage_name'] == 'Ожидание'
le_masque &= sorted_df['activity_name'] == 'Назначить интервью с руководителем'
df_wait_2 = sorted_df[le_masque]
df_wait_2['result_name'].unique()

array(['Интервью с руководителем', 'Обработка'], dtype=object)

In [63]:
le_masque = sorted_df['stage_name'] == 'Ожидание'
le_masque &= sorted_df['activity_name'] == 'Назначить время на оформление/медосмотр'
df_wait_3 = sorted_df[le_masque]
df_wait_3['result_name'].unique()

array(['Назначить время на оформление/медосмотр'], dtype=object)

In [64]:
le_masque = sorted_df['stage_name'] == 'Ожидание'
le_masque &= sorted_df['activity_name'] == 'Провести первичную обработку'
df_wait_4 = sorted_df[le_masque]
df_wait_4['result_name'].unique()

array(['Обработка'], dtype=object)

In [65]:
le_masque = sorted_df['stage_name'] == 'Ожидание'
le_masque &= sorted_df['activity_name'] == 'Узнать результаты приема'
df_wait_5 = sorted_df[le_masque]
df_wait_5['result_name'].unique()

array(['Оформление'], dtype=object)

12) Стадия 'Не прошел СБ'

In [66]:
le_masque = sorted_df['stage_name'] == 'Не прошел СБ'
df_dont = sorted_df[le_masque]
df_dont['activity_name'].unique()

array([nan, 'Вывести из черного списка'], dtype=object)

In [67]:
le_masque = sorted_df['stage_name'] == 'Не прошел СБ'
le_masque &= sorted_df['activity_name'] == 'Вывести из черного списка'
df_dont_1 = sorted_df[le_masque]
df_dont_1['result_name'].unique()

array([nan, 'В белый список'], dtype=object)

13) Стадия 'Мы отказали'

In [70]:
le_masque = sorted_df['stage_name'] == 'Мы отказали'
df_hz = sorted_df[le_masque]
df_hz['activity_name'].unique()

array([nan], dtype=object)

14) Стадия 'Черный список'

In [71]:
le_masque = sorted_df['stage_name'] == 'Черный список'
df_black = sorted_df[le_masque]
df_black['activity_name'].unique()

array(['Вывести из черного списка'], dtype=object)

In [72]:
le_masque = sorted_df['stage_name'] == 'Черный список'
le_masque &= sorted_df['activity_name'] == 'Вывести из черного списка'
df_black_1 = sorted_df[le_masque]
df_black_1['result_name'].unique()

array(['В белый список', nan], dtype=object)

15) Стадия 'Кадровый резерв'

In [75]:
le_masque = sorted_df['stage_name'] == 'Кадровый резерв'
df_res = sorted_df[le_masque]
df_res['activity_name'].unique()

array([nan], dtype=object)